version: "3"
services:
  app:
    build: ./
    container_name: SmartQuiz-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartquizappDB3
      SPRING_DATASOURCE_PASSWORD: Run2safex
      SPRING_DATASOURCE_USERNAME: postgres
    depends_on:
      - db
    networks:
      - smartquiz-api
  db:
    image: postgres:latest
    container_name: postgresDB2
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Run2safex
      POSTGRES_DB: smartquizappDB3
    networks:
      - smartquiz-api
networks:
  smartquiz-api:
    driver: bridge